doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '15'

        profiling_collect_backtrace: '%kernel.debug%'
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        dql:
            datetime_functions:
                #  date: DoctrineExtensions\Query\Mysql\Date
                #  date_format: DoctrineExtensions\Query\Mysql\DateFormat
                #  dateadd: DoctrineExtensions\Query\Mysql\DateAdd
                #  datesub: DoctrineExtensions\Query\Mysql\DateSub
                #  datediff: DoctrineExtensions\Query\Mysql\DateDiff
                #  day: DoctrineExtensions\Query\Mysql\Day
                #  dayname: DoctrineExtensions\Query\Mysql\DayName
                #  dayofweek: DoctrineExtensions\Query\Mysql\DayOfWeek
                #  dayofyear: DoctrineExtensions\Query\Mysql\DayOfYear
                #  week: DoctrineExtensions\Query\Mysql\Week
                #  weekday: DoctrineExtensions\Query\Mysql\WeekDay
                #  weekofyear: DoctrineExtensions\Query\Mysql\WeekOfYear
                #  year: DoctrineExtensions\Query\Mysql\Year
                #  yearmonth: DoctrineExtensions\Query\Mysql\YearMonth
                #  yearweek: DoctrineExtensions\Query\Mysql\YearWeek


                second: DoctrineExtensions\Query\Postgresql\Second
                minute: DoctrineExtensions\Query\Postgresql\Minute
                hour: DoctrineExtensions\Query\Postgresql\Hour
                day: DoctrineExtensions\Query\Postgresql\Day
                month: DoctrineExtensions\Query\Postgresql\Month
                year: DoctrineExtensions\Query\Postgresql\Year
                date_format: DoctrineExtensions\Query\Postgresql\DateFormat
                at_time_zone: DoctrineExtensions\Query\Postgresql\AtTimeZoneFunction
                date_part: DoctrineExtensions\Query\Postgresql\DatePart
                extract: DoctrineExtensions\Query\Postgresql\ExtractFunction
                date_trunc: DoctrineExtensions\Query\Postgresql\DateTrunc
                date: DoctrineExtensions\Query\Postgresql\Date


when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
